---
title: "Codebook for data in Hoffart, Jarecki, Duthil, & Rieskamp"
author: "Jana B. Jarecki & Elina Lutz"
date: "`r Sys.Date()`"
output: html_document
  # github_document:
  #   css: css.css
  # html_document:
  #   toc: false
  #   toc_depth: 4
  #   toc_float: true
  #   code_folding: "hide"
  #   self_contained: false
  #   css: css.css
link-citations: yes
always_allow_html: true
---

This document contains codebooks explaining the variables and labels of the data files study1.csv and study2.csv in the folder data/processed.


```{r setup, echo = FALSE, warning = FALSE, message = FALSE}
# No need to change anything in this block
if (!require(pacman)) install.packages("pacman")
pacman::p_load(data.table, codebook, labelled, sjlabelled, dplyr, ggthemes)
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  error = TRUE,
  echo = FALSE,
  fig.margin = TRUE,
  fig.height = 1.4,
  fig.width = 3,
  echo = FALSE
)
pander::panderOptions("table.split.table", Inf)
ggplot2::theme_set(ggthemes::theme_tufte(base_family = "sans", ticks = FALSE))
```

```{r meta_info}
# Define a list with information about the authors, affiliation, methods of data collection, and so forth (called meta information)
meta_info <- list(
  citation = "Hoffart, Jarecki, Duthil, & Rieskamp",
  creator =list( # maybe use affiliation only in the end?
    "@type" = "Person", 
    givenName = "Janine C.", 
    familyName = "Hoffart",
    email = "janine.hoffart@gmail.com",
    
    "@type" = "Person",
    givenName = "Jana B.",
    familyName = "Jarecki",
    email = "jj@janajarecki.com", 
    affiliation = list(
      "@type" = "Organization",
      name = "University of Basel, Switzerland"),
    
    "@type" = "Person", 
    givenName = "Gilles", 
    familyName = "Duthil",
    
    "@type" = "Person", 
    givenName = "Jörg", 
    familyName = "Rieskamp"
    ),
  spatialCoverage = "laboratory",
  temporalCoverage = "NA"
  # measurementTechnique = "Experimental data with human participants, within-subjects design",
  # funder = "Center for Economic Psychology, University of Basel",
  # keywords = c("online study", "risky choice", "risky gamble", "decisions from experience", "psychology", "cognition", "cognitive modeling", "heuristics", "bayesian cognitive model")
  )

# Function that defines how to print the codebook, only change
# it if you want more details to be printed
print_options <- list(
  detailed_variables = FALSE,
  detailed_scales = FALSE,
  survey_overview = TRUE,
  missingness_report = TRUE,
  metadata_table = TRUE,
  metadata_json = TRUE
    )
```

# Study 1
```{r codebook study1}
# Preparation
study1 <- fread("../processed/study1.csv")
fa <- c("condition", "gambleid", "samplesizecat", "gambletype")
study1[, c(fa) := lapply(.SD, factor), .SDcols = fa]
setcolorder(study1, c("id", "condition", "trial", "gambleid", "gamblex", "gamblep", "gambletype", "samplesizecat", "samplesize"))

# var_label
variables_explained <- list(
  id = "Participant identifier",
  condition = "Within-subjects condition",
  # block = "Block number in a phase: 1 in familiarization, 7 in five-trial phase, 1 in one-shot phase",
  # round = "Round number, consecutive number, independent of block or phase",
   trial = "Trial number for each participant",
   gamblep = "Probability of the risky gamble stimulus",
   gamblex = "Outcome of the risky gamble stimulus",
   value = "Respondents' evaluation of the gamble",
   gambleid = "Identifier of the gamble",
   gambletype = "Type of gamble (two-outcome gambles with either a gain or a zero outcome)", # part in brackets necessary?
   samplesize = "Number of samples the participant drew; is NA if condition is 'description'",
   confidence = "Respondents' self-reported confidence in their evaluation",
   samplesizecat = "Level of sample size; is '--' if condition is 'description'"

#   state = "Number of points accumulated until this trial",
#   budget = "Point requirement in this round",
#   stimulus0 = "Describes the first option (risky gamble) in this round in xpy notation: firstOutcome_prFirst_secondOutcome",
#   stimulus1 = "Describes the second option (risky gamble) in this round in xpy notation: firstOutcome_prFirst_secondOutcome", 
#   terminal_state = "Total points by the end of this round",
#   choice_1isHighVar = "Choice in this trial",
#   success = "Did the terminal_state (total points) exceed the budget (requirement) by the end of this round?",
#   successes = "Number of rounds with a success up to this round",
#   rt_ms = "Reaction time in this trial in milliseconds",
#   xh = "Outcome of the high-variance option in this round",
#   ph = "Probability of x_h",
#   yh = "Second outcome of high-variance option, pr(y_h) = 1 - p_h",
#   xl = "Outcome of the low-variance option in this round",
#   pl = "Probability of x_l",
#   yl = "Second outcome of low-variance option, pr(y_l) = 1 - p_l",
#   gneezy_potter = "One-shot choice (asked once after the choice phase): Which part of the 100 pennys do you wish to invest in the lottery? With probability 67% the lottery pays zero. You earn the amount that you did not invest. With probability 33% the lottery pays 2.5X. You earn +2.5 x X plus the amount that you did not invest.",
#   layout_featurecolor = "Which feature is shown in which color in this round. The colors are dark grey (RGB #D9D9D9, grey85) or light grey (RGB #737373, gray45)",
#   layout_stimulusposition_01 = "In which order stimulus0 and stimulus 1 are shown in this round (left or right on screen)"
)

var_label(study1) <- variables_explained

# val_labels
# val_labels(study1$choice_1isHighVar) <- c(
#   "Low-variance option" = 0,
#   "High-variance option"  = 1)
# val_labels(study1$success) <- c(
#   "No" = 0,
#   "Yes"  = 1)

# Meta data
metadata(study1) <- meta_info
metadata(study1)$name <- "study1"
metadata(study1)$description <- "Choice data from the decision from experience experiment by Hoffart, Jarecki, Duthil, and Rieskamp investigating how the size of the sample that people experience affects their preferences between risky options. Study 1: Possible outcomes known before sampling phase."
   
# Generating the codebook
codebook(study1,
  detailed_variables = FALSE,
  detailed_scales = FALSE,
  missingness_report = FALSE,
  survey_overview = TRUE)
```

# Study 2
```{r codebook study2}

# Preparation
study2 <- fread("../processed/study2.csv")
# fa <- c("condition", "gambleid", "samplesizecat", "gambletype") # already defined for study1
study2[, c(fa) := lapply(.SD, factor), .SDcols = fa]
setcolorder(study2, c("id", "condition", "trial", "gambleid", "gamblex", "gamblep", "gambletype", "samplesizecat", "samplesize"))

# var_label
var_label(study2) <- variables_explained

# Meta data
metadata(study2) <- meta_info
metadata(study2)$name <- "study2"
metadata(study2)$description <- "Choice data from the decision from experience experiment by Hoffart, Jarecki, Duthil, and Rieskamp investigating how the size of the sample that people experience affects their preferences between risky options. Study 2: Possible outcomes learned during sampling phase."

# Generating the codebook
compact_codebook(study2)
```
